// useGdriveAuth.ts — Google OAuth + token lifecycle for the Drive sync.
//
// Step 2 of the useGdriveSync split. This hook owns the
// AUTH domain: token storage (tkGet/tkSet/tkClear), the account hint,
// the PKCE/CSRF helpers, gdriveGetToken (popup on Android/desktop,
// redirect on iOS standalone), gdriveReconnect, the iOS save-tap
// reauth piggyback, the OAuth-return capture (pendingOAuth), and the
// startup silent token refresh.
//
// What deliberately STAYS in useGdriveSync.ts:
//   - the pendingOAuth DISPATCHER effect (it calls gdriveSave /
//     gdriveRestore / gdriveSaveQuiet — sync-domain functions);
//   - gdriveSaveQuiet's own in-flow silent re-auth (embedded in the
//     quiet-save state machine).
//
// Composition: useGdriveSync calls useGdriveAuth internally — App.tsx
// is unchanged. The storage helpers are exported at module level
// because the sync-domain retry paths (401/403 → tkClear → re-auth)
// also need them.
//
// ⚠️ SECURITY INVARIANTS (CLAUDE.md §19) — all preserved verbatim:
//   - iOS standalone MUST use window.location.replace +
//     response_type=token (no PKCE, no initTokenClient — both fail).
//   - The CSRF state is generated by pkceGenerateVerifier and checked
//     fail-closed in utils/oauthReturn.ts.
//   - Token access only via tkGet/tkSet/tkClear.

import React from "react";
import {
  SK,
  GDRIVE_CLIENT_ID,
  GDRIVE_SCOPE,
  GDRIVE_PENDING_STALE_MS,
} from "../constants.ts";
import { recordOAuthEvent } from "../utils/oauthDiag.ts";
import { fetchWithTimeout } from "../utils/gdriveApi.ts";
import { redactApiKeys } from "./useAiAutoFill.ts";
import { IS_IOS_STANDALONE } from "../utils/platform.ts";

var useState = React.useState,
  useEffect = React.useEffect,
  useRef = React.useRef;

// Track the timestamp of the last user gesture (pointer
// down OR key down) globally so triggerIosAutosaveReauth can verify
// that a `save()` call originates from a user-interactive context. This
// blocks the cleanup paths (30-day trash purge at mount, etc.) from
// silently kicking off an OAuth redirect on cold start.
var lastUserGestureTs = 0;

// Canonical definition moved to src/utils/platform.ts (was
// duplicated with App.tsx). Imported at the top of this module for its own
// use AND re-exported here so useGdriveSync's `import { IS_IOS_STANDALONE }
// from "./useGdriveAuth.ts"` keeps working unchanged.
export { IS_IOS_STANDALONE };

export function tkGet(): string | null {
  try {
    return (IS_IOS_STANDALONE ? localStorage : sessionStorage).getItem("gdrive-tk");
  } catch { return null; }
}
export function tkSet(v: string): void {
  // CodeQL js/clear-text-storage-of-sensitive-information — accepted risk.
  // Static PWA with no backend: the OAuth access token must live on-device to
  // call googleapis.com directly. localStorage is used only on iOS standalone
  // (sessionStorage doesn't survive the redirect OAuth flow); every other
  // platform uses sessionStorage. CSP locks down script-src to prevent XSS.
  try { (IS_IOS_STANDALONE ? localStorage : sessionStorage).setItem("gdrive-tk", v); } catch {}
}
export function tkClear(): void {
  try { localStorage.removeItem("gdrive-tk"); } catch {}
  try { sessionStorage.removeItem("gdrive-tk"); } catch {}
  // NB: deliberately does NOT clear `gdrive-account-hint` here. tkClear
  // runs on every 401/403 token expiry, and the whole point of the hint
  // is to skip Google's account picker on the very next
  // re-auth. The hint is cleared only on an EXPLICIT account switch
  // (gdrive-force-select → hintClear in gdriveGetToken). The persisted
  // email is the user's own, on their own device, used solely as a
  // login_hint — a negligible PII footprint that doesn't justify
  // breaking the picker-skip on every routine token refresh.
}

// Persistent account hint so the user doesn't have to
// re-select their Google account on every re-auth. Stored as the email
// address fetched from drive/v3/about after the first successful token.
// Passed to subsequent initTokenClient / OAuth URL calls as login_hint
// so Google skips the account chooser when the hinted account is signed
// in. Cleared when the user explicitly switches account via Settings →
// "Switch Google account" (which sets gdrive-force-select).
export function hintGet(): string {
  try { return localStorage.getItem("gdrive-account-hint") || ""; } catch { return ""; }
}
export function hintSet(email: string): void {
  if (!email) return;
  try { localStorage.setItem("gdrive-account-hint", email); } catch {}
}
export function hintClear(): void {
  try { localStorage.removeItem("gdrive-account-hint"); } catch {}
}
// Best-effort: fetch the authenticated user's email and persist it.
// Uses drive/v3/about which works with the drive.appdata scope we
// already hold (no extra consent required). Silent on any failure —
// the worst case is the user sees the account picker on the next
// re-auth, i.e. the behaviour before the hint existed.
export function captureAccountHint(token: string): void {
  if (!token || hintGet()) return;
  try {
    fetch("https://www.googleapis.com/drive/v3/about?fields=user", {
      headers: { Authorization: "Bearer " + token },
    })
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (data: any) {
        var email = data && data.user && data.user.emailAddress;
        if (typeof email === "string" && email.indexOf("@") > 0) {
          hintSet(email);
        }
      })
      .catch(function () {});
  } catch (_e) {}
}

// Returns the SPA root path (strips any static .html filename so the OAuth
// redirect always lands on index.html, even if the user navigated to help.html
// or another sub-page before triggering the auth flow.
export function spaRoot(): string {
  var p = String(window.location.pathname).replace(/\/[^/]+\.html$/, "") || "/";
  return p.endsWith("/") ? p : p + "/";
}

// `pkceGenerateVerifier` produces a cryptographically-random
// base64url string used as the OAuth CSRF state. The iOS
// flow uses `response_type=token`, not PKCE — so the verifier alone
// is what we need. The previous `pkceChallengeFromVerifier` (SHA-256
// challenge) helper was test-only dead code and was removed.
function pkceBase64Url(bytes: Uint8Array): string {
  var s = "";
  for (var i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i] || 0);
  return String(btoa(s)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
export function pkceGenerateVerifier(): string {
  // RFC 7636 requires 43–128 chars from [A-Z a-z 0-9 - . _ ~].
  // 32 random bytes → 43 base64url chars.
  var bytes = new Uint8Array(32);
  // Fail loud if the runtime has no crypto API. Otherwise
  // the chained `||` would resolve to undefined → `.getRandomValues`
  // would throw immediately, but only as a TypeError. Worse, a future
  // refactor that surfaces a fallback could silently keep `bytes` as
  // zeroes → CSRF state predictable. Throw explicitly so any consumer
  // can route the user to a real OS browser instead of a hardened
  // / no-Web-Crypto environment.
  var c = (globalThis.crypto || (window as any).crypto);
  if (!c || typeof c.getRandomValues !== "function") {
    throw new Error("Web Crypto unavailable — cannot generate CSRF state");
  }
  c.getRandomValues(bytes);
  return pkceBase64Url(bytes);
}

export function useGdriveAuth({
  t,
  setGdriveStatus,
  setImportModal,
}: {
  t: (k: string) => string;
  setGdriveStatus: (s: string | null) => void;
  setImportModal: (v: boolean) => void;
}) {
  var driveTokenRef = useRef<string | null>(null);
  var _poa = useState<{ tk: string; ac: string } | null>(null),
    pendingOAuth = _poa[0],
    setPendingOAuth = _poa[1];

  // Register a single capturing pointer/key listener
  // that stamps `lastUserGestureTs`. Powers the user-gesture-proximity
  // guard in triggerIosAutosaveReauth — see the helper for rationale.
  useEffect(function () {
    function _mark() { lastUserGestureTs = Date.now(); }
    window.addEventListener("pointerdown", _mark, { passive: true });
    window.addEventListener("keydown", _mark, { passive: true });
    return function () {
      window.removeEventListener("pointerdown", _mark);
      window.removeEventListener("keydown", _mark);
    };
  }, []);

  // OAuth redirect handling (fires once on mount for iOS standalone redirect flow).
  // Two paths supported:
  //  - PKCE code flow (preferred, new): __PENDING_GDRIVE_CODE__ is set; we exchange it for a token.
  //  - Legacy raw token (back-compat): __PENDING_GDRIVE_TOKEN__ is set; we use it as-is.
  useEffect(function () {
    if (!window.__PENDING_GDRIVE_ACTION__) return;
    var ac = window.__PENDING_GDRIVE_ACTION__;
    window.__PENDING_GDRIVE_ACTION__ = null;

    if (window.__PENDING_GDRIVE_CODE__ && window.__PENDING_GDRIVE_VERIFIER__) {
      var code = window.__PENDING_GDRIVE_CODE__;
      var verifier = window.__PENDING_GDRIVE_VERIFIER__;
      var redirect = window.__PENDING_GDRIVE_REDIRECT__
        || (window.location.origin + spaRoot());
      window.__PENDING_GDRIVE_CODE__ = null;
      window.__PENDING_GDRIVE_VERIFIER__ = null;
      window.__PENDING_GDRIVE_REDIRECT__ = null;
      // Settings opens on save/restore so the user can confirm the picker
      // and watch the status line, but a pure reconnect is a no-op as far
      // as Drive content is concerned — the user clicked the banner from
      // wherever they were and expects to stay put once the token is
      // refreshed.
      if (ac !== "reconnect") setImportModal(true);
      setGdriveStatus(t("st_connecting"));
      var body = new URLSearchParams();
      body.set("code", code);
      body.set("client_id", GDRIVE_CLIENT_ID);
      body.set("code_verifier", verifier);
      body.set("grant_type", "authorization_code");
      body.set("redirect_uri", redirect);
      fetchWithTimeout("https://oauth2.googleapis.com/token", {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: body.toString(),
      })
        .then(function (r) { return r.json(); })
        .then(function (resp: any) {
          if (!resp || resp.error || !resp.access_token) {
            setGdriveStatus(
              t("err_prefix") + " OAuth: " + ((resp && (resp.error_description || resp.error)) || "no token"),
            );
            setTimeout(function () { setGdriveStatus(null); }, 5000);
            return;
          }
          try {
            tkSet(JSON.stringify({ t: resp.access_token, x: Date.now() + 3500000 }));
          } catch (_e) {}
          driveTokenRef.current = resp.access_token;
          // Persist the email so future re-auth round-trips
          // can pass it as login_hint and skip the Google account picker.
          captureAccountHint(resp.access_token);
          setPendingOAuth({ tk: resp.access_token, ac: ac });
        })
        .catch(function (e) {
          // Redact any echoed secret before display.
          var rawMsg = e && e.message ? e.message : "exchange failed";
          setGdriveStatus(t("err_prefix") + " OAuth: " + redactApiKeys(String(rawMsg)));
          setTimeout(function () { setGdriveStatus(null); }, 5000);
        });
      return;
    }

    if (window.__PENDING_GDRIVE_TOKEN__) {
      var tk = window.__PENDING_GDRIVE_TOKEN__;
      window.__PENDING_GDRIVE_TOKEN__ = null;
      // Capture the email from the iOS redirect token too,
      // matching the PKCE-code branch above.
      captureAccountHint(tk);
      // Reconnect / autosave: keep the user on the view they came from
      // (no Settings panel pop-up). `autosave` is the iOS
      // workaround — see triggerIosAutosaveReauth below.
      if (ac !== "reconnect" && ac !== "autosave") setImportModal(true);
      setPendingOAuth({ tk: tk, ac: ac });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Silent token refresh on startup (non-iOS standalone)
  useEffect(function () {
    if (
      IS_IOS_STANDALONE ||
      localStorage.getItem("cave-autosave") !== "1" ||
      !localStorage.getItem("gdrive-auto-fid")
    )
      return;
    try {
      var _ck = JSON.parse(tkGet() || "null");
      if (_ck && _ck.x > Date.now() + 120000) return;
    } catch (_e) {}
    var _done = false;
    function _silentAuth() {
      if (_done) return;
      try {
        var _hint = hintGet();
        var cl = window.google.accounts.oauth2.initTokenClient(Object.assign({
          client_id: GDRIVE_CLIENT_ID,
          scope: GDRIVE_SCOPE,
          callback: function (r: any) {
            if (_done) return;
            _done = true;
            if (!r.error && r.access_token) {
              driveTokenRef.current = r.access_token;
              try {
                tkSet(
                  JSON.stringify({
                    t: r.access_token,
                    x: Date.now() + 3500000,
                  }),
                );
              } catch (_e) {}
              captureAccountHint(r.access_token);
            }
          },
          error_callback: function () {
            _done = true;
          },
        }, _hint ? { hint: _hint } : {}));
        cl.requestAccessToken({ prompt: "" });
      } catch (_e) {
        _done = true;
      }
    }
    var _t = setTimeout(function () {
      if (
        window.google &&
        window.google.accounts &&
        window.google.accounts.oauth2
      ) {
        _silentAuth();
      } else {
        // NO Subresource Integrity (SRI) on gsi/client.
        // Google publishes this script at an unversioned URL and rolls
        // updates on their own cadence for security/compliance reasons.
        // Pinning a hash here would break Drive auth the moment Google
        // pushes a new build (https://developers.google.com/identity/gsi
        // explicitly states SRI is unsupported). Defense-in-depth instead:
        // CSP whitelists `accounts.google.com` in script-src (index.html),
        // HTTPS-only transport, and connect-src restricts what the script
        // can call out to. JSZip on cdnjs IS pinned with SRI — that one
        // ships at a versioned URL so the hash holds.
        var s = document.createElement("script");
        s.src = "https://accounts.google.com/gsi/client";
        s.onload = function () {
          setTimeout(_silentAuth, 300);
        };
        s.onerror = function () {};
        document.head.appendChild(s);
      }
    }, 2500);
    return function () {
      clearTimeout(_t);
    };
  }, []);

  // LABEL-CONTRACT:start drive-oauth-scope — see scripts/label-contracts.json
  function gdriveGetToken(action: any, forceInteractive?: boolean) {
    return new Promise(function (ok, no) {
      var forceSelect = !!localStorage.getItem("gdrive-force-select");
      if (forceSelect) {
        localStorage.removeItem("gdrive-force-select");
        // The user explicitly asked to switch account
        // (Settings → Changer de compte Google). Wipe the persisted
        // login hint so Google shows the picker instead of silently
        // re-using the previously-stored email. The new account's
        // email is captured automatically after the auth callback.
        hintClear();
      }
      var loginHint = !forceSelect ? hintGet() : "";
      if (IS_IOS_STANDALONE) {
        if (!forceSelect) {
          var _ct = driveTokenRef.current;
          if (!_ct) {
            try {
              var _ls = JSON.parse(tkGet() || "null");
              if (_ls && _ls.x > Date.now() + 60000) _ct = _ls.t;
            } catch (_e) {}
          }
          if (_ct) {
            ok(_ct);
            return;
          }
        }
        // iOS standalone: window.location.replace navigates within the PWA
        // webview (no Safari popup). initTokenClient always opens a popup which
        // leaves the PWA → callback never fires → stuck on "Connexion...".
        // PKCE (response_type=code) requires client_secret on Web Application
        // clients. response_type=token is the only viable approach without a
        // backend or a native/desktop OAuth client registration.
        var st = pkceGenerateVerifier(); // cryptographically-random CSRF state
        var redirectUri = window.location.origin + spaRoot();
        localStorage.setItem("gdrive-pending", action || "save");
        // Stamp the start time so triggerIosAutosaveReauth
        // (and the mount-time guard in App.tsx) can recognise a stale
        // pending — e.g. the user closed the OAuth tab, Google bounced
        // back without a hash, or the redirect chain died mid-flight.
        // Without this, gdrive-pending stayed set forever and every
        // subsequent save-tap auto-save was silently blocked.
        localStorage.setItem("gdrive-pending-ts", String(Date.now()));
        localStorage.setItem("gdrive-state", st);
        localStorage.removeItem("gdrive-pkce-verifier");
        localStorage.removeItem("gdrive-pkce-redirect");
        try {
          var _bkp = localStorage.getItem(SK);
          if (_bkp) {
            localStorage.setItem(SK + "-bkp", _bkp);
            localStorage.setItem(SK + "-bkp-ts", String(Date.now()));
          }
        } catch (_e) {}
        var _p =
          "client_id=" + encodeURIComponent(GDRIVE_CLIENT_ID) +
          "&redirect_uri=" + encodeURIComponent(redirectUri) +
          "&response_type=token" +
          "&scope=" + encodeURIComponent(GDRIVE_SCOPE) +
          "&state=" + encodeURIComponent(st) +
          "&include_granted_scopes=true" +
          // Per-action prompt strategy with escalation.
          //   - forceSelect: account picker (Settings → switch account).
          //   - forceInteractive: caller signalled a previous silent
          //     attempt failed (e.g. Reconnect within 60 s of the last
          //     attempt) → escalate to the account picker.
          //   - everything else (incl. "reconnect" first attempt): no
          //     prompt → Google decides; silent (no UI) when SSO +
          //     scope are still valid, interactive otherwise. Restores
          //     the original behaviour where
          //     Reconnect was a silent one-tap action in the common
          //     case. Two later attempts forced UI on every Reconnect; the
          //     escalation below now only fires when the user actually
          //     needs to interact (rare in practice).
          ((forceSelect || forceInteractive)
            ? "&prompt=select_account"
            : "") +
          // Skip the Google account picker when we already
          // know which account the user signed in with last time.
          (loginHint ? "&login_hint=" + encodeURIComponent(loginHint) : "");
        // Stamp the diagnostic right before we leave the
        // app — surfaces in Settings → Drive when (if) the user returns
        // without a token.
        recordOAuthEvent(
          "redirect-start",
          action || "save",
          (forceSelect || forceInteractive) ? "prompt=select_account" : "prompt=silent",
        );
        // eslint-disable-next-line tabac-local/string-only-method
        window.location.replace(
          "https://accounts.google.com/o/oauth2/v2/auth?" + _p,
        );
        return;
      }
      function doAuth() {
        try {
          var client = window.google.accounts.oauth2.initTokenClient(Object.assign({
            client_id: GDRIVE_CLIENT_ID,
            scope: GDRIVE_SCOPE,
            callback: function (resp: any) {
              if (resp.error) {
                no(new Error(resp.error_description || resp.error));
                return;
              }
              // Capture the user's email so subsequent
              // re-auth round-trips can pass it as login_hint and skip
              // the account chooser. captureAccountHint short-circuits
              // if the hint is already set.
              captureAccountHint(resp.access_token);
              ok(resp.access_token);
            },
            error_callback: function (err: any) {
              no(new Error(err.message || t("err_prefix")));
            },
          }, loginHint ? { hint: loginHint } : {}));
          client.requestAccessToken({
            // Same escalation logic as the iOS branch
            // above. Default to silent (prompt=""); only force the
            // account picker when forceSelect / forceInteractive ask
            // for it. Reconnect's first attempt is silent so the popup
            // bounces back without UI when SSO + scope are valid.
            prompt: (forceSelect || forceInteractive)
              ? "select_account"
              : "",
          });
        } catch (e) {
          no(new Error(t("err_prefix") + ": " + (e as Error).message));
        }
      }
      if (
        window.google &&
        window.google.accounts &&
        window.google.accounts.oauth2
      ) {
        doAuth();
      } else {
        var s = document.createElement("script");
        s.src = "https://accounts.google.com/gsi/client";
        s.onload = function () {
          setTimeout(doAuth, 500);
        };
        s.onerror = function () {
          no(new Error(t("err_google_unavailable")));
        };
        document.head.appendChild(s);
      }
    });
  }
  // LABEL-CONTRACT:end drive-oauth-scope

  // Re-tuned since: the Reconnect button behind the
  // "Drive session expired" banner so the user no longer has to fake
  // a manual backup just to renew the session.
  function gdriveReconnect() {
    setGdriveStatus(t("st_connecting"));
    // Reconnect is ALWAYS interactive (prompt=
    // select_account). The earlier "silent first with escalation"
    // didn't survive contact with real iOS PWA reality: Google
    // returns to the PWA without a token even when SSO seems valid
    // (cookies isolated to the webview, scope checks, etc.), so the
    // silent first tap is essentially guaranteed to fail for many
    // users — leaving the banner stuck. Users then tap Reconnect
    // again expecting it to work, but the 60 s escalation window
    // can lapse or be misread.
    //
    // The user explicitly taps Reconnect = explicit user intent
    // to fix this NOW. A single-tap picker (1 tap on the avatar
    // when login_hint pre-selects the account) is faster than a
    // silent attempt that visibly does nothing. Silent reconnection
    // is still available implicitly via triggerIosAutosaveReauth
    // (every form save / mutation piggybacks silently when Google
    // allows) — that's the path that gives the "no Google window"
    // experience on routine edits.
    return gdriveGetToken("reconnect", true).then(function (tk: any) {
      var token = tk as string;
      driveTokenRef.current = token;
      try {
        tkSet(JSON.stringify({ t: token, x: Date.now() + 3500000 }));
      } catch (_e) {}
      setGdriveStatus(null);
      return token;
    }).catch(function (e: any) {
      // Redact echoed secrets.
      var raw = String((e && e.message) || t("err_prefix")).substring(0, 200);
      setGdriveStatus(redactApiKeys(raw));
      setTimeout(function () { setGdriveStatus(null); }, 3000);
    });
  }

  // IOS auto-save workaround.
  //
  // On iOS standalone PWA the silent token refresh path (initTokenClient
  // with prompt="") is unavailable — the redirect flow leaves the PWA,
  // there are no popups, and there is no refresh token (Google's
  // implicit grant doesn't issue them). So after ~1 h of usage the
  // Drive token expires and auto-save silently breaks until the user
  // taps the "Reconnect" banner.
  //
  // The workaround piggybacks on the user gesture of tapping Save on
  // any form (tobacco / pipe / accessory / session / wish): we run the
  // local save normally, then if the Drive token has effectively
  // expired AND the user has previously engaged with Drive AND
  // auto-save is enabled, we silently kick off the iOS OAuth redirect
  // with `ac="autosave"`. The redirect flicker is short (Google
  // bounces back immediately when SSO + consent are already in place);
  // on return the `autosave` dispatcher captures the token and fires
  // gdriveSaveQuiet — no modal, no status banner. From the user's POV
  // they tapped Save and the Drive sync re-armed itself.
  //
  // No-ops on Android / desktop (silent refresh already works there
  // via gdriveSaveQuiet's existing branch). No-op when the user hasn't
  // engaged with Drive yet (we don't surprise a never-Drive user with
  // a redirect they didn't opt into). No-op when the token has
  // > 5 minutes left (the normal auto-save will handle it cleanly).
  function triggerIosAutosaveReauth(): void {
    if (!IS_IOS_STANDALONE) return;
    // User-gesture-proximity guard: only fire when this call originates
    // from an interactive context (pointer or key within the last 2 s).
    // Blocks the cleanup paths (30-day trash purge, migration save) from
    // silently kicking off an OAuth redirect at cold start.
    if (Date.now() - lastUserGestureTs > 2000) return;
    try {
      if (localStorage.getItem("cave-autosave") !== "1") return;
      // OAuth round-trip already in flight — don't queue another.
      // But if the pending was set > 60 s ago, treat
      // it as dead and clean up. A genuine in-flight OAuth round
      // never takes that long (Google + user reading consent caps
      // at ~30 s); the only way to overshoot is a dropped chain
      // (user closed the OAuth tab, Google bounced without a hash,
      // network died after the redirect). Without this, a single
      // dropped attempt blocks every future save-tap auto-save.
      if (localStorage.getItem("gdrive-pending")) {
        var pts = parseInt(localStorage.getItem("gdrive-pending-ts") || "0", 10);
        if (pts > 0 && Date.now() - pts > GDRIVE_PENDING_STALE_MS) {
          localStorage.removeItem("gdrive-pending");
          localStorage.removeItem("gdrive-pending-ts");
        } else {
          return;
        }
      }
      // Token still good for > 5 min → let the normal auto-save run.
      // Parse failure gets its own catch — a corrupted
      // token cache used to bubble to the outer catch's bare `return`, which
      // silently blocked EVERY future save-tap reauth (the corrupt
      // value was never cleared, so every pass died at the same line).
      // Clearing it here means the next pass sees an empty cache and
      // proceeds to the redirect, which is exactly the repair needed.
      var st: any = null;
      try { st = JSON.parse(tkGet() || "null"); }
      catch (_pe) { try { tkClear(); } catch (_ce) {} st = null; }
      if (st && st.x > Date.now() + 5 * 60 * 1000) return;
      // User never engaged with Drive → no implicit consent to redirect.
      var engaged = !!(
        localStorage.getItem("gdrive-auto-fid") ||
        localStorage.getItem("gdrive-fid") ||
        localStorage.getItem("cave-autosave-ts")
      );
      if (!engaged) return;
    } catch (_e) { return; }
    // gdriveGetToken("autosave") writes gdrive-pending + initiates the
    // redirect. The Promise never resolves locally (navigation aborts);
    // the dispatcher (in useGdriveSync) picks it up on return.
    gdriveGetToken("autosave").catch(function () {});
  }

  return {
    driveTokenRef,
    pendingOAuth,
    setPendingOAuth,
    gdriveGetToken,
    gdriveReconnect,
    triggerIosAutosaveReauth,
  };
}
